/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adtarea3;

import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.ucanaccess.converters.Functions;

/**
 *
 * @author mmart
 */
public class ActualizarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarEmpleado
     */
    public ActualizarEmpleado() {
        initComponents();
        this.setTitle("Actualizar Empleados");
        Image icono = Toolkit.getDefaultToolkit().getImage("./src/imagenes/icono.png");
        this.setIconImage(icono);
        setLocationRelativeTo(null);
        
        listadoNombreEmpleados();
    }
    
    // Creamos un método que devuelva un objeto de tipo Connection para que
    // pueda ser utilizado por el resto de métodos de la clase
    
    private Connection Conexion(){
        
        Connection conexion = null;
        // Conexión a la base de datos de la tienda de ropa
        String connectionUrl= "jdbc:ucanaccess://./src\\BBDD\\tiendaropa.mdb" ;
        
        try {
            conexion = DriverManager.getConnection(connectionUrl);
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
        
        return conexion;
        
    }
    
    // Códigos y nombres empleados para ComboBox
    
    private void listadoNombreEmpleados(){
        
        try {
            
            Connection conexion = this.Conexion();
            
            Statement consulta = conexion.createStatement();
            
            ResultSet resultado = consulta.executeQuery("SELECT * FROM empleados");
            
            while (resultado.next()){
                
                String nombre = resultado.getString("nombre");

                jComboBoxListadoEmpleados.addItem(nombre);
            }
            
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListadoEmpleados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnActualizarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(744, 400));
        setSize(new java.awt.Dimension(744, 380));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(744, 380));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(adtarea3.ADTarea3App.class).getContext().getResourceMap(ActualizarEmpleado.class);
        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jComboBoxListadoEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un empleado" }));
        jComboBoxListadoEmpleados.setName("jComboBoxListadoEmpleados"); // NOI18N
        jComboBoxListadoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListadoEmpleadosActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jTextFieldCodigo.setText(resourceMap.getString("jTextFieldCodigo.text")); // NOI18N
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.setName("jTextFieldCodigo"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldNombre.setText(resourceMap.getString("jTextFieldNombre.text")); // NOI18N
        jTextFieldNombre.setName("jTextFieldNombre"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextFieldTelefono.setText(resourceMap.getString("jTextFieldTelefono.text")); // NOI18N
        jTextFieldTelefono.setName("jTextFieldTelefono"); // NOI18N

        btnActualizar.setText(resourceMap.getString("btnActualizar.text")); // NOI18N
        btnActualizar.setName("btnActualizar"); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnActualizarP.setText(resourceMap.getString("btnActualizarP.text")); // NOI18N
        btnActualizarP.setName("btnActualizarP"); // NOI18N
        btnActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxListadoEmpleados, 0, 363, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarP)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxListadoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar)
                    .addComponent(btnActualizarP))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPActionPerformed
        String nombre = jTextFieldNombre.getText();
        String telefono = jTextFieldTelefono.getText();
        String codigo = jTextFieldCodigo.getText();

        if (nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe rellenar el campo de nombre");
        }else if (telefono.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Debe rellenar el campo de teléfono");
        }else if (!Functions.isNumeric(telefono)){
            JOptionPane.showMessageDialog(null, "El campo teléfono debe ser un campo numérico ");
        }else{
            
             try {

                Connection conexion = this.Conexion();
                PreparedStatement consulta = conexion.prepareStatement("UPDATE empleados SET nombre=?,telefono=? WHERE Codigo_empleado=?");

                long telefonoNumero = Long.parseLong(telefono);
                long codigoNumero = Long.parseLong(codigo);
                
                consulta.setString(1, nombre);
                consulta.setLong(2, telefonoNumero);
                consulta.setLong(3, codigoNumero);
                consulta.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Se han actualizado los datos del empleado correctamente");
                
                jComboBoxListadoEmpleados.addItem(jTextFieldNombre.getText());
                jComboBoxListadoEmpleados.removeItemAt(jComboBoxListadoEmpleados.getSelectedIndex() );
                jComboBoxListadoEmpleados.setSelectedIndex(0);
                

                jTextFieldCodigo.setText("");
                jTextFieldNombre.setText("");
                jTextFieldTelefono.setText("");
      
            } catch (SQLException sqle) {
                sqle.getMessage();
            }
        
        }
    }//GEN-LAST:event_btnActualizarPActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        try {

            Connection conexion = this.Conexion();

            Statement consulta = conexion.createStatement();

            consulta.executeUpdate("UPDATE empleados SET nombre=\'"+jTextFieldNombre.getText() +
                "\', telefono=\'" + jTextFieldTelefono.getText() +
                "\' WHERE Codigo_empleado=\'" + jTextFieldCodigo.getText()+"\'");

            JOptionPane.showMessageDialog(null, "Se han actualizado los datos del empleado correctamente");

            // Actualizamos el listado de empleados en el ComboBox y reiniciamos los campos

            jComboBoxListadoEmpleados.addItem(jTextFieldNombre.getText());
            jComboBoxListadoEmpleados.removeItemAt(jComboBoxListadoEmpleados.getSelectedIndex() );              
            jComboBoxListadoEmpleados.setSelectedIndex(0);

            jTextFieldCodigo.setText("");
            jTextFieldNombre.setText("");
            jTextFieldTelefono.setText("");

        } catch (SQLException sqle) {
            sqle.getMessage();
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jComboBoxListadoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListadoEmpleadosActionPerformed

        try {

            Connection conexion = this.Conexion();

            Statement consulta = conexion.createStatement();

            ResultSet resultado = consulta.executeQuery("SELECT * FROM empleados WHERE nombre = \'"+jComboBoxListadoEmpleados.getSelectedItem().toString()+"\'");

            while (resultado.next()){

                int codigo = resultado.getInt("Codigo_empleado");
                String nombre = resultado.getString("nombre");
                long telefono = resultado.getLong("telefono");

                //Asignamos los resultados a los JTexts
                jTextFieldCodigo.setText(Integer.toString(codigo));
                jTextFieldNombre.setText(nombre);
                jTextFieldTelefono.setText(String.valueOf(telefono));
            }

        } catch (SQLException sqle) {
            sqle.getMessage();
        }

    }//GEN-LAST:event_jComboBoxListadoEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarP;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jComboBoxListadoEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
