/*
 * ADTarea3View.java
 */

package adtarea3;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;



/**
 * The application's main frame.
 */
public class ADTarea3View extends FrameView {

    
    public ADTarea3View(SingleFrameApplication app){
        super(app);

        initComponents();
        this.getFrame().setIconImage(Toolkit.getDefaultToolkit().getImage("./src/imagenes/icono.png"));
        existeTablaEmpleados();
        existeTablaVentas();

    }
    
    // Creamos un método que devuelva un objeto de tipo Connection para que
    // pueda ser utilizado por el resto de métodos de la clase
    
    private Connection Conexion(){
        
        Connection conexion = null;
        // Conexión a la base de datos de la tienda de ropa
        String connectionUrl= "jdbc:ucanaccess://./src\\BBDD\\tiendaropa.mdb" ;
        
        try {
            conexion = DriverManager.getConnection(connectionUrl);
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
        
        return conexion;
        
    }
    
  

    
    //Métodos que comprueban si exiten las tablas. Este método nos servirá también
    // para deshabilitar los botones en caso de que no estén creadas. Nos 
    
    public void existeTablaEmpleados(){
        
        String empleados = "empleados";
        try {
            Connection conexion = this.Conexion();
            Statement stmt = conexion.createStatement();
            
            DatabaseMetaData datos = this.Conexion().getMetaData();
            ResultSet rs = datos.getTables(null, null, "%", null);
            
            while (rs.next()){
                String tabla = rs.getString(3);

                if (empleados.equals(tabla)){
                    existeEmpleados = true;
                }
            }
            
            if (!existeEmpleados){
                JOptionPane.showMessageDialog(null, "Debe crear la tabla empleados");
                btnActualizarEmpleado.setEnabled(false);
                btnInsertarEmpleado.setEnabled(false);
                btnMostrarEmpleados.setEnabled(false); 
            }
            
            
        } catch (SQLException slqe) {
            slqe.getMessage();
        }
        
    }
    
    public void existeTablaVentas(){
         String ventas = "ventas";
        try {
            Connection conexion = this.Conexion();
            Statement stmt = conexion.createStatement();
            
            DatabaseMetaData datos = this.Conexion().getMetaData();
            ResultSet rs = datos.getTables(null, null, "%", null);
            
            while (rs.next()){
                String tabla = rs.getString(3);

                if (ventas.equals(tabla)){
                    existeVentas = true;
                }
            }
            
            if (!existeVentas){
                JOptionPane.showMessageDialog(null, "Debe crear la tabla ventas");
                btnActualizarVenta.setEnabled(false);
                btnInsertarVenta.setEnabled(false);
                btnMostrarVentas.setEnabled(false);
                
            }else {
                btnActualizarVenta.setEnabled(true);
                btnInsertarVenta.setEnabled(true);
                btnMostrarVentas.setEnabled(true);
                
            }

        } catch (SQLException slqe) {
            slqe.getMessage();
        }
        
    }

 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btnCrearTablaEmpleados = new javax.swing.JButton();
        btnCrearTablaVentas = new javax.swing.JButton();
        btnInsertarEmpleado = new javax.swing.JButton();
        btnActualizarEmpleado = new javax.swing.JButton();
        btnMostrarEmpleados = new javax.swing.JButton();
        btnInsertarVenta = new javax.swing.JButton();
        btnMostrarVentas = new javax.swing.JButton();
        btnActualizarVenta = new javax.swing.JButton();
        btnVentasEmpleados = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(adtarea3.ADTarea3App.class).getContext().getResourceMap(ADTarea3View.class);
        btnCrearTablaEmpleados.setText(resourceMap.getString("btnCrearTablaEmpleados.text")); // NOI18N
        btnCrearTablaEmpleados.setName("btnCrearTablaEmpleados"); // NOI18N
        btnCrearTablaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaEmpleadosActionPerformed(evt);
            }
        });

        btnCrearTablaVentas.setText(resourceMap.getString("btnCrearTablaVentas.text")); // NOI18N
        btnCrearTablaVentas.setMaximumSize(new java.awt.Dimension(185, 32));
        btnCrearTablaVentas.setMinimumSize(new java.awt.Dimension(185, 32));
        btnCrearTablaVentas.setName("btnCrearTablaVentas"); // NOI18N
        btnCrearTablaVentas.setPreferredSize(new java.awt.Dimension(185, 32));
        btnCrearTablaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaVentasActionPerformed(evt);
            }
        });

        btnInsertarEmpleado.setText(resourceMap.getString("btnInsertarEmpleado.text")); // NOI18N
        btnInsertarEmpleado.setMaximumSize(new java.awt.Dimension(185, 32));
        btnInsertarEmpleado.setMinimumSize(new java.awt.Dimension(185, 32));
        btnInsertarEmpleado.setName("btnInsertarEmpleado"); // NOI18N
        btnInsertarEmpleado.setPreferredSize(new java.awt.Dimension(185, 32));
        btnInsertarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarEmpleadoActionPerformed(evt);
            }
        });

        btnActualizarEmpleado.setText(resourceMap.getString("btnActualizarEmpleado.text")); // NOI18N
        btnActualizarEmpleado.setName("btnActualizarEmpleado"); // NOI18N
        btnActualizarEmpleado.setPreferredSize(new java.awt.Dimension(185, 32));
        btnActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmpleadoActionPerformed(evt);
            }
        });

        btnMostrarEmpleados.setText(resourceMap.getString("btnMostrarEmpleados.text")); // NOI18N
        btnMostrarEmpleados.setMaximumSize(new java.awt.Dimension(185, 32));
        btnMostrarEmpleados.setMinimumSize(new java.awt.Dimension(185, 32));
        btnMostrarEmpleados.setName("btnMostrarEmpleados"); // NOI18N
        btnMostrarEmpleados.setPreferredSize(new java.awt.Dimension(185, 32));
        btnMostrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEmpleadosActionPerformed(evt);
            }
        });

        btnInsertarVenta.setText(resourceMap.getString("btnInsertarVenta.text")); // NOI18N
        btnInsertarVenta.setMaximumSize(new java.awt.Dimension(185, 32));
        btnInsertarVenta.setMinimumSize(new java.awt.Dimension(185, 32));
        btnInsertarVenta.setName("btnInsertarVenta"); // NOI18N
        btnInsertarVenta.setPreferredSize(new java.awt.Dimension(185, 32));
        btnInsertarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarVentaActionPerformed(evt);
            }
        });

        btnMostrarVentas.setText(resourceMap.getString("btnMostrarVentas.text")); // NOI18N
        btnMostrarVentas.setMaximumSize(new java.awt.Dimension(185, 32));
        btnMostrarVentas.setMinimumSize(new java.awt.Dimension(185, 32));
        btnMostrarVentas.setName("btnMostrarVentas"); // NOI18N
        btnMostrarVentas.setPreferredSize(new java.awt.Dimension(185, 32));
        btnMostrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasActionPerformed(evt);
            }
        });

        btnActualizarVenta.setText(resourceMap.getString("btnActualizarVenta.text")); // NOI18N
        btnActualizarVenta.setMaximumSize(new java.awt.Dimension(185, 32));
        btnActualizarVenta.setMinimumSize(new java.awt.Dimension(185, 32));
        btnActualizarVenta.setName("btnActualizarVenta"); // NOI18N
        btnActualizarVenta.setPreferredSize(new java.awt.Dimension(185, 32));
        btnActualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVentaActionPerformed(evt);
            }
        });

        btnVentasEmpleados.setText(resourceMap.getString("btnVentasEmpleados.text")); // NOI18N
        btnVentasEmpleados.setName("btnVentasEmpleados"); // NOI18N
        btnVentasEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVentasEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnCrearTablaEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearTablaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearTablaVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearTablaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnInsertarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnVentasEmpleados)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(adtarea3.ADTarea3App.class).getContext().getActionMap(ADTarea3View.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(statusMessageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statusAnimationLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel))
                .addGap(5, 5, 5)
                .addComponent(jLabel1))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTablaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaEmpleadosActionPerformed
        try {
            if (!existeEmpleados){
                Connection conexion = this.Conexion();
            
            Statement stmt = conexion.createStatement();
            stmt.execute("CREATE TABLE empleados (Codigo_empleado COUNTER PRIMARY KEY, nombre TEXT(255), telefono LONG)");
            JOptionPane.showMessageDialog(null, "Se ha creado la tabla EMPLEADOS de forma existosa");
            btnCrearTablaEmpleados.setEnabled(false);
            btnActualizarEmpleado.setEnabled(true);
            btnInsertarEmpleado.setEnabled(true);
            btnMostrarEmpleados.setEnabled(true);
            }else {
                JOptionPane.showMessageDialog(null, "La tabla Empleados ya ha sido creada anteriormente");
                btnCrearTablaEmpleados.setEnabled(false);
            }
     
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
    }//GEN-LAST:event_btnCrearTablaEmpleadosActionPerformed

    private void btnCrearTablaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaVentasActionPerformed
        try {
            
            if (!existeVentas){
                Connection conexion = this.Conexion();
            
            Statement stmt = conexion.createStatement();
            stmt.execute("CREATE TABLE ventas (Codigo_producto COUNTER PRIMARY KEY, nombre TEXT(255), codigo_empleado long, unidades long)");
            JOptionPane.showMessageDialog(null, "Se ha creado la tabla VENTAS de forma existosa");
            btnCrearTablaVentas.setEnabled(false);
            btnActualizarVenta.setEnabled(true);
            btnInsertarVenta.setEnabled(true);
            btnMostrarVentas.setEnabled(true);
            }else {
                JOptionPane.showMessageDialog(null, "La tabla Ventas ya ha sido creada anteriormente");
                btnCrearTablaVentas.setEnabled(false);
            }
            
               
            
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
    }//GEN-LAST:event_btnCrearTablaVentasActionPerformed

    private void btnInsertarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarEmpleadoActionPerformed
        InsertarEmpleado ie = new InsertarEmpleado();
        ie.setVisible(true);
    }//GEN-LAST:event_btnInsertarEmpleadoActionPerformed

    private void btnInsertarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarVentaActionPerformed
        InsertarVenta iv = new InsertarVenta();
        iv.setVisible(true);
    }//GEN-LAST:event_btnInsertarVentaActionPerformed

    private void btnMostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadosActionPerformed
        ListadoEmpleados le = new ListadoEmpleados();
        le.setVisible(true);
    }//GEN-LAST:event_btnMostrarEmpleadosActionPerformed

    private void btnMostrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasActionPerformed
        ListadoVentas lv = new ListadoVentas();
        lv.setVisible(true);
    }//GEN-LAST:event_btnMostrarVentasActionPerformed

    private void btnActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoActionPerformed
        ActualizarEmpleado ae = new ActualizarEmpleado();
        ae.setVisible(true);
    }//GEN-LAST:event_btnActualizarEmpleadoActionPerformed

    private void btnActualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVentaActionPerformed
        ActualizarVenta av = new ActualizarVenta();
        av.setVisible(true);
    }//GEN-LAST:event_btnActualizarVentaActionPerformed

    private void btnVentasEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasEmpleadosActionPerformed
        VentasEmpleados ve = new VentasEmpleados();
        ve.setVisible(true);
    }//GEN-LAST:event_btnVentasEmpleadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEmpleado;
    private javax.swing.JButton btnActualizarVenta;
    private javax.swing.JButton btnCrearTablaEmpleados;
    private javax.swing.JButton btnCrearTablaVentas;
    private javax.swing.JButton btnInsertarEmpleado;
    private javax.swing.JButton btnInsertarVenta;
    private javax.swing.JButton btnMostrarEmpleados;
    private javax.swing.JButton btnMostrarVentas;
    private javax.swing.JButton btnVentasEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
    private boolean existeEmpleados = false;
    private boolean existeVentas = false;
    

}
