/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adtarea3;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author mmart
 */
public class VentasEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form VentasEmpleados
     */
    public VentasEmpleados() {
        initComponents();
        setTitle("Ventas por Empleado");
        Image icono = Toolkit.getDefaultToolkit().getImage("./src/imagenes/icono.png");
        this.setIconImage(icono);
        listadoVentas();
        setLocationRelativeTo(null);
        jTextAreaListadoEmpleados.setLineWrap(true);
    }
    
    // Creamos un método que devuelva un objeto de tipo Connection para que
    // pueda ser utilizado por el resto de métodos de la clase
    
    private Connection Conexion(){
        
        Connection conexion = null;
        // Conexión a la base de datos de la tienda de ropa
        String connectionUrl= "jdbc:ucanaccess://./src\\BBDD\\tiendaropa.mdb" ;
        
        try {
            conexion = DriverManager.getConnection(connectionUrl);
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
        
        return conexion;
        
    }
    
    // Códigos y nombres empleados para ComboBox
    
    private void listadoVentas(){
        
        try {
            
            Connection conexion = this.Conexion();
            
            Statement consulta = conexion.createStatement();
            
            ResultSet resultado = consulta.executeQuery("SELECT nombre FROM ventas GROUP BY nombre");
            
            while (resultado.next()){
                
                String nombre = resultado.getString("nombre");

                jComboBoxListadoProductos.addItem(nombre);
            }
            
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListadoProductos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaListadoEmpleados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(adtarea3.ADTarea3App.class).getContext().getResourceMap(VentasEmpleados.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jComboBoxListadoProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un producto" }));
        jComboBoxListadoProductos.setName("jComboBoxListadoProductos"); // NOI18N
        jComboBoxListadoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListadoProductosActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextAreaListadoEmpleados.setEditable(false);
        jTextAreaListadoEmpleados.setColumns(20);
        jTextAreaListadoEmpleados.setRows(5);
        jTextAreaListadoEmpleados.setName("jTextAreaListadoEmpleados"); // NOI18N
        jScrollPane2.setViewportView(jTextAreaListadoEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(btnCancelar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxListadoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxListadoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83)
                        .addComponent(btnCancelar))
                    .addComponent(jScrollPane2))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jComboBoxListadoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListadoProductosActionPerformed

        try {
            
            //Reiniciamos el TextArea a fin de que no se vayan añadiendo los resultados
           jTextAreaListadoEmpleados.setText("");

            Connection conexion = this.Conexion();

            Statement consulta = conexion.createStatement();

            ResultSet resultado = consulta.executeQuery("SELECT * FROM ventas WHERE nombre=\'"+
                                                        jComboBoxListadoProductos.getSelectedItem().toString()+"\'");
            while (resultado.next()){

                Long codigoProducto = resultado.getLong("codigo_empleado");
                
                ResultSet resultado2 = consulta.executeQuery("SELECT nombre FROM empleados WHERE Codigo_empleado=\'"+
                                                            codigoProducto+"\'");             
                while (resultado2.next()){
                    String nombre = resultado2.getString("nombre");
                    
                    jTextAreaListadoEmpleados.append(nombre);
                    jTextAreaListadoEmpleados.append(System.getProperty("line.separator"));
                }  
            }
        } catch (SQLException sqle) {
            sqle.getMessage();
        }
        
    }//GEN-LAST:event_jComboBoxListadoProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jComboBoxListadoProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaListadoEmpleados;
    // End of variables declaration//GEN-END:variables
}
